# Generated by Django 5.0.7 on 2024-07-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="book_img",
            field=models.ImageField(upload_to="books/"),
        ),
    ]
