# Generated by Django 5.0.7 on 2024-07-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0005_alter_bookmodel_book_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookallotmentmodel",
            name="status",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
